org: caiiiycuk
app: jsdos-backend
service: jsdos-repository

package:
  exclude:
    - 'node_modules/**'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  memorySize: 256
  versionFunctions: false
  environment:
    SESSION_TABLE: "v2_dzsession"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.SESSION_TABLE}"

functions:
  ssoUrl:
    handler: src/sso-url.ssoUrl
    name: jsdos-sls-ssoUrl
    events:
      - http:
          path: /sso/url
          method: get
          cors: true
  ssoLogin:
    handler: src/sso-login.ssoLogin
    name: jsdos-sls-ssoLogin
    events:
      - http:
          path: /sso/login
          method: get
          cors: true
  ssoLogout:
    handler: src/sso-logout.ssoLogout
    name: jsdos-sls-ssoLogout
    events:
      - http:
          path: /sso/logout
          method: get
          cors: true

resources:
  Resources:
    dzsession:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: nonce
            AttributeType: S
        KeySchema:
          -
            AttributeName: nonce
            KeyType: HASH
        TableName: ${self:provider.environment.SESSION_TABLE}
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-plugin-typescript
