name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install -g yarn
        cd sls && yarn && cd ..
        mkdir sls/private
        echo "export const NONCE=\"\";" > sls/private/sso.ts
        echo "export const SECRET=\"\";" >> sls/private/sso.ts
        yarn
        yarn run eslint . --ext ts --max-warnings 0
        yarn run build
